### ISSUE TITLE
urllib.urlencode is not compatible with Python 3

### ISSUE THREAD

**Issue by aa7955** [IBM-Cloud/sql-query-clients#3] opened 2018-02-08 23:02 UTC
https://github.com/IBM-Cloud/sql-query-clients/blob/1c973d5d1d27dab4840dd98798bfbd8be4bbf616/Python/ibmcloudsql/SQLQuery.py#L54

**Comment by torsstei** [comment] 2018-02-09 07:58
Thanks. The issue is now fixed and I tested successfully with both, Python2 and Python3. New v 0.1.3 on pypi.

**Closed by torsstei** 2018-02-09 07:58 UTC
